### ISSUE TITLE
As a teacher, I need to know when are my next class groups

### ISSUE THREAD

**Issue by maujart** [maujart/natashkola#36]
Let's say we would define 4 groups

- start of the first class
- occurence in a week 
- language 
- level
- number of classes in total

**Comment by NATKV** [comment]
https://docs.google.com/document/d/140MqO2jYFGbIt9DbqiTcgNKOo-KeddKDQCFjrf8e5_8/edit

**Comment by maujart** [comment]
I have no access on it, please give access to maujart@gmail.com

**Comment by NATKV** [comment]
https://docs.google.com/document/d/14lDLaExQ6f1o73YecJvL5kt7pKtO4Gw7A2pyfBAKkxI/edit
https://docs.google.com/document/d/1XxjP4Qr5c7u7uDOjSUb0QgFimL5EgRAyxUM9WNpIGwM/edit
