### ISSUE TITLE
Find icons for the "why us" page

### ISSUE THREAD

**Issue by maujart** [maujart/natashkola#58]
please use this website

https://thenounproject.com/search/?q=computer&i=3534140

expected result : 
a set of 8 icons (preferably of the style, or from the same author to keep a style pattern)

**Comment by NATKV** [comment]
I modified "Why us" page. 
https://docs.google.com/document/d/14lDLaExQ6f1o73YecJvL5kt7pKtO4Gw7A2pyfBAKkxI/edit

**Comment by maujart** [comment]
not relevant anymore
